version: "3.9"

services:

  image-processor:
    container_name: image-processor
    build: ./
    volumes:
      - ${ORIGIN_PHOTOS_TEMP}:${DEST_PHOTOS_TEMP}
      - ${ORIGIN_PHOTOS}:${DEST_PHOTOS}
    environment:
      - SOURCE_DIR=${DEST_PHOTOS_TEMP}
      - DEST_DIR=${DEST_PHOTOS}
    command: ["python", "process_images.py"]