version: "3.9"

services:

  image-processor:
    container_name: image-processor
    build: ./
    volumes:
      - /mnt/sda/jrbb/FOTOS_TEMPORAL/:/data/FOTOS_TEMP/
      - /mnt/sda/jrbb/FOTOS/:/data/FOTOS/
    environment:
      - SOURCE_DIR=/data/FOTOS_TEMP/
      - DEST_DIR=/data/FOTOS/
    command: ["python", "process_images.py"]